# O cheie foarte lung? pentru a securiza token-ul (trebuie sa aiba minim 256 biti)
jwt.secret=4e075be94ac3f771634aba3dd5b139ba33165e2855d9a95ac5ff028cda491aea
# Token-ul expir? dup? o or? (3600000 ms)
jwt.expiration=3600000

# Configurarea CORS ca s? permitem aplica?iei de React s? comunice cu noi
app.cors.allowed-origins=http://localhost:5173